//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PgmD.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.ApplicationPrivilegeAttributes = new HashSet<ApplicationPrivilegeAttribute>();
            this.RoleTypes = new HashSet<RoleType>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual ICollection<ApplicationPrivilegeAttribute> ApplicationPrivilegeAttributes { get; set; }
        public virtual ICollection<RoleType> RoleTypes { get; set; }
    }
}
