//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PgmD.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationPrivilegeAttribute
    {
        public string Context { get; set; }
        public int AppID { get; set; }
        public Nullable<int> MaxDuration { get; set; }
        public Nullable<int> AllPrivileges { get; set; }
        public Nullable<int> GrantPrivilegeMask { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
