//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PgmD.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hierarchy
    {
        public Hierarchy()
        {
            this.Subhierarchies = new HashSet<Subhierarchy>();
            this.Subhierarchies1 = new HashSet<Subhierarchy>();
            this.HierarchyNodes = new HashSet<HierarchyNode>();
        }
    
        public string Context { get; set; }
        public string HierarchyName { get; set; }
        public int VersionID { get; set; }
        public int Root { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedBySourceSystem { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedBySourceSystem { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual HierarchyVersion HierarchyVersion { get; set; }
        public virtual OrgEntity OrgEntity { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual Personnel Personnel1 { get; set; }
        public virtual ICollection<Subhierarchy> Subhierarchies { get; set; }
        public virtual ICollection<Subhierarchy> Subhierarchies1 { get; set; }
        public virtual ICollection<HierarchyNode> HierarchyNodes { get; set; }
    }
}
