//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PgmD.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HierarchicalAC
    {
        public string Context { get; set; }
        public int Root { get; set; }
        public int Node { get; set; }
        public string Grantee { get; set; }
        public string GranteeSourceSystem { get; set; }
        public int AppID { get; set; }
        public int RoleTypeID { get; set; }
        public int Privileges { get; set; }
        public string Reason { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedBySourceSystem { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedBySourceSystem { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string NotificationStatus { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
    
        public virtual RoleTypePrivilege RoleTypePrivilege { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual Personnel Personnel1 { get; set; }
        public virtual Personnel Personnel2 { get; set; }
        public virtual OrgEntity OrgEntity { get; set; }
        public virtual OrgEntity OrgEntity1 { get; set; }
    }
}
