//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PgmD.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HierarchyNode
    {
        public HierarchyNode()
        {
            this.HierarchyNodes1 = new HashSet<HierarchyNode>();
            this.Subhierarchies = new HashSet<Subhierarchy>();
        }
    
        public string Context { get; set; }
        public string HierarchyName { get; set; }
        public int VersionID { get; set; }
        public int Root { get; set; }
        public int Node { get; set; }
        public string ParentContext { get; set; }
        public string ParentHierarchyName { get; set; }
        public Nullable<int> ParentVersionID { get; set; }
        public Nullable<int> ParentRoot { get; set; }
        public Nullable<int> Parent { get; set; }
        public int InternalSortPosition { get; set; }
        public Nullable<decimal> ExternalSortPosition { get; set; }
        public byte Type { get; set; }
        public string Label { get; set; }
        public string OrgDetail { get; set; }
    
        public virtual Hierarchy Hierarchy { get; set; }
        public virtual ICollection<HierarchyNode> HierarchyNodes1 { get; set; }
        public virtual HierarchyNode HierarchyNode1 { get; set; }
        public virtual OrgEntity OrgEntity { get; set; }
        public virtual ICollection<Subhierarchy> Subhierarchies { get; set; }
    }
}
