//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PgmD.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OERolePersonnel
    {
        public int OEID { get; set; }
        public int AppID { get; set; }
        public int RoleTypeID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string PersonID { get; set; }
        public string SourceSystem { get; set; }
        public string RoleTitle { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedBySourceSystem { get; set; }
        public string JobCode { get; set; }
    
        public virtual OrgEntity OrgEntity { get; set; }
        public virtual RoleType RoleType { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual Personnel Personnel1 { get; set; }
    }
}
