//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PgmD.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgEntity
    {
        public OrgEntity()
        {
            this.HierarchicalACs = new HashSet<HierarchicalAC>();
            this.HierarchicalACs1 = new HashSet<HierarchicalAC>();
            this.Hierarchies = new HashSet<Hierarchy>();
            this.OERolePersonnels = new HashSet<OERolePersonnel>();
            this.HierarchyNodes = new HashSet<HierarchyNode>();
        }
    
        public int ID { get; set; }
        public string SourcingHierarchyContext { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public string Alias { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedBySourceSystem { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedBySourceSystem { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<HierarchicalAC> HierarchicalACs { get; set; }
        public virtual ICollection<HierarchicalAC> HierarchicalACs1 { get; set; }
        public virtual ICollection<Hierarchy> Hierarchies { get; set; }
        public virtual ICollection<OERolePersonnel> OERolePersonnels { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual Personnel Personnel1 { get; set; }
        public virtual ICollection<HierarchyNode> HierarchyNodes { get; set; }
    }
}
