//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PgmD.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        public Personnel()
        {
            this.HierarchicalACs = new HashSet<HierarchicalAC>();
            this.HierarchicalACs1 = new HashSet<HierarchicalAC>();
            this.HierarchicalACs2 = new HashSet<HierarchicalAC>();
            this.Hierarchies = new HashSet<Hierarchy>();
            this.Hierarchies1 = new HashSet<Hierarchy>();
            this.OERolePersonnels = new HashSet<OERolePersonnel>();
            this.OERolePersonnels1 = new HashSet<OERolePersonnel>();
            this.OrgEntities = new HashSet<OrgEntity>();
            this.OrgEntities1 = new HashSet<OrgEntity>();
        }
    
        public string ID { get; set; }
        public string SourceSystem { get; set; }
        public string DisplayName { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Middle { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string AcctDept { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<byte> IsUSPerson { get; set; }
        public Nullable<byte> IsBoeingEmployee { get; set; }
        public string Status { get; set; }
        public string JobCode { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<HierarchicalAC> HierarchicalACs { get; set; }
        public virtual ICollection<HierarchicalAC> HierarchicalACs1 { get; set; }
        public virtual ICollection<HierarchicalAC> HierarchicalACs2 { get; set; }
        public virtual ICollection<Hierarchy> Hierarchies { get; set; }
        public virtual ICollection<Hierarchy> Hierarchies1 { get; set; }
        public virtual ICollection<OERolePersonnel> OERolePersonnels { get; set; }
        public virtual ICollection<OERolePersonnel> OERolePersonnels1 { get; set; }
        public virtual ICollection<OrgEntity> OrgEntities { get; set; }
        public virtual ICollection<OrgEntity> OrgEntities1 { get; set; }
    }
}
