//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PgmD.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleType
    {
        public RoleType()
        {
            this.OERolePersonnels = new HashSet<OERolePersonnel>();
            this.RoleTypePrivileges = new HashSet<RoleTypePrivilege>();
        }
    
        public int AppID { get; set; }
        public int RoleTypeID { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ICollection<OERolePersonnel> OERolePersonnels { get; set; }
        public virtual ICollection<RoleTypePrivilege> RoleTypePrivileges { get; set; }
    }
}
