//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PgmD.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleTypePrivilege
    {
        public RoleTypePrivilege()
        {
            this.HierarchicalACs = new HashSet<HierarchicalAC>();
        }
    
        public string Context { get; set; }
        public int AppID { get; set; }
        public int RoleTypeID { get; set; }
        public int Privileges { get; set; }
        public string Description { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual ICollection<HierarchicalAC> HierarchicalACs { get; set; }
        public virtual RoleType RoleType { get; set; }
    }
}
